apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-shield-deployment
  labels:
    app: git-shield
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-shield
  template:
    metadata:
      labels:
        app: git-shield
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: git-shield
        image: ghcr.io/ratteperk/gitshield:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4123
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 4123
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4123
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5