apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: git-shield-monitor
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: git-shield
  namespaceSelector:
    any: true  
  endpoints:
  - port: http
    path: /metrics 