apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.7
    helm:
      values: |
        adminPassword: "admin"
        
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local:80
              access: proxy
              isDefault: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:     
    - CreateNamespace=true
