apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: default
  source:
    chart: alertmanager
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.17.0
    helm:
      values: |
        alertmanagerSpec:
          secrets:
            - alertmanager-telegram-secret
          config:
            global:
              resolve_timeout: 5m
            route:
              receiver: 'telegram'
              group_by: ['alertname', 'severity']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 1h
            receivers:
            - name: 'telegram'
              telegram_configs:
              - bot_token_file: /etc/alertmanager/secrets/bot_token
                chat_id: '931027118'
                send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true